task: korean_spacing_20210101
log_path: logs
bert_model: monologg/kobert
train_data_path: /content/drive/MyDrive/train_test/train.txt
test_data_path: /content/drive/MyDrive/train_test/data/test.txt
max_len: 128
train_batch_size: 64
eval_batch_size: 64
dropout_rate: 0.1
gpus: 8
distributed_backend: ddp